// flow-typed signature: 0ac2dcbd1b1bbf572cfb4529d47e4c17
// flow-typed version: <<STUB>>/rollup-plugin-sourcemaps_v^0.4.2/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-sourcemaps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-sourcemaps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-sourcemaps/dist/rollup-plugin-sourcemaps.es' {
  declare module.exports: any;
}

declare module 'rollup-plugin-sourcemaps/dist/rollup-plugin-sourcemaps' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-sourcemaps/dist/rollup-plugin-sourcemaps.es.js' {
  declare module.exports: $Exports<'rollup-plugin-sourcemaps/dist/rollup-plugin-sourcemaps.es'>;
}
declare module 'rollup-plugin-sourcemaps/dist/rollup-plugin-sourcemaps.js' {
  declare module.exports: $Exports<'rollup-plugin-sourcemaps/dist/rollup-plugin-sourcemaps'>;
}
